### ISSUE TITLE
Leapp blocks CTRL+R keybind (and others?) after SSO window closes for Chrome browser

### ISSUE THREAD

**Issue by Plasma** [Noovolari/leapp#185]
**Describe the bug**
When AWS SSO dialog appears and after you perform the login, the SSO dialog closes, and from now onwards, pressing CTRL+R keybind in a regular browser like Chrome (at least, and unrelated to Leapp app) does not work.

I haven't tested whether other keybinds are affected. It appears Leapp is maybe "blocking" this keybind from Chrome (and maybe other apps/keybinds?).

To remedy the issue, re-show the Leapp window (via Leapp icon -> Show) and CTRL+R works again.

**Leapp Version**
Add the version of your Leapp (you can find it under taskbar -> about or Leapp -> about on MacOS X)

**To Reproduce**
1. Open Leapp, and hide it so it sits in the system tray
2. Click on the Leapp tray icon and choose to turn on a profile
3. The SSO window appears to retrieve the credentials - complete the SSO sign-in process
4. Once the SSO window has closed, try and press CTRL+R in a Chrome browser tab (for example) and notice the page does not reload
5. If you now cause Leapp to Show (tray icon -> Show) and then close the dialog, the CTRL+R Chrome keybind works again

**Expected behavior**
Leapp should not be causing the CTRL+R (and maybe other keybinds) from working after the AWS SSO window is dismissed.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Leapp Version 0.7.3

**Additional context**
I wonder whether the SSO login window is still "visible" or capturing keybinds even though its dismissed/closed?

The CTRL+R keybind is only prevented when the SSO window closes, up until that point, the keybind works fine.

**Comment by Plasma** [comment]
Hi @pethron I have a feeling this may be due to https://github.com/Noovolari/leapp/blob/master/src/app/services/aws-sso-oidc.service.ts#L165 causing the `browser-window-blur` event to not be fired in https://github.com/Noovolari/leapp/blob/master/electron/main.ts#L113 which restores CTRL+R/F5 keybind functionality when the SSO window is dismissed.

I can confirm that if the SSO window pops up, if I close it the bug is also there, so I think that is the issue.

**Comment by praider** [comment]
If it helps, I've experienced a similar issue. F5 usage was blocked system wide (Chrome, Visual Studio, etc.,). I killed the app to perform an update and F5 is now working again (although I haven't tried signing into AWS yet)

**Comment by ericvilla** [comment]
Hi! I think a possible solution is to add `this.ssoWindow.hide();` before https://github.com/Noovolari/leapp/blob/4e645f37f047abda2c768aee54795950df58af7e/src/app/services/aws-sso-oidc.service.ts#L179

In that way, it fires the on blur event for the browserWindow before closing it. I've already tried it and it works. Let me know if I'm missing something. @urz9999 what do you think about that?

**Comment by urz9999** [comment]
I've checked some examples online which confirm your theory, for example https://www.tabnine.com/code/javascript/functions/electron/BrowserWindow/hide
It seems that when you want to close a window you also need to let it lose focus: this behavior typically happens when an app is configured to also for hiding in MacOS instead of closing.

**Comment by ericvilla** [comment]
Fixed with the last v0.7.4 release

**Comment by drov0** [comment]
Hello, I am still seeing the issue on ubuntu 20 with leapp 0.8.0, did we get a regression ?

**Comment by ericvilla** [comment]
HI @drov0, thanks for reporting! I guess that's because you fail in an error condition, where we forgot to call BrowserWindow's hide() method:

https://github.com/Noovolari/leapp/blob/4e645f37f047abda2c768aee54795950df58af7e/src/app/services/aws-sso-oidc.service.ts#L204

To confirm that's the case, we've to double-check it by doing a smoke test. We'll fix it for the next release.
May I ask you to provide the application logs? In that way, I think we can confirm what I've supposed the issue to be 🙂

**Comment by drov0** [comment]
@ericvilla thanks for the quick response ! Where can I see the logs ? I wonder if the issue is tied to the browser or the actual window (where we can see and configure sessions). If I close the window I get the keybind, but if it's just minimized, the keybind is no tthere.

**Comment by ericvilla** [comment]
You're welcome! You can find logs path [here](https://docs.leapp.cloud/troubleshooting/app-data/#logs-file).
Btw, I'm pretty sure the issue is related to the Electron BrowserWindow.

**Comment by drov0** [comment]
I'm afraid I don't have any logs. I have a bunch of files in ~/.config/Leapp/ but no log.logs

**Comment by drmikecrowe** [comment]
@ericvilla  I think this is still an issue (somehow), tho it may be unrelated:  When I minimize Leapp to the tray, I lose ^R/F5 functionality in all my browsers.  If I leave the Leapp window open, all works fine.

LMK if you want me to submit a new issue or if this is a corner case of this one

**Comment by ericvilla** [comment]
Sure @drmikecrowe! I'll let you know if it is necessary to open a new issue or if it is strictly correlated to this one

**Comment by fancywriter** [comment]
I am reproducing it again on version 0.9.0. When window is minimized in tray, CTRL+R doesn't work. If not, it works. Looks very weird.

**Comment by fancywriter** [comment]
@ericvilla I don't see anything in `.config/Leapp/logs/log.log`, but I see in stdout (or stderr) when running Leapp from terminal:
```
CommandOrControl+R is pressed: Shortcut Disabled
```
Each time when I am trying to press Ctrl + R (and it doesn't work). The Leapp window is minimized to tray, shouldn't be in focus.

**Comment by Plasma** [comment]
It seems to be a regression yes, although only occurs after SSO sign-on completes (before I then dismiss Leapp), if I minimize Leapp to tray and re-open it and re-minimize it seems fine again.

**Comment by fancywriter** [comment]
@Plasma is there any version older than 0.9.0 which is not affected? Not sure I really need the newest...

**Comment by drmikecrowe** [comment]
@ericvilla @Plasma --- this is definitely still an issue with 0.10.0 on Linux/Ubuntu (Gnome 20.10):

```
 ~  uname -a                                                                                                                                                                                       15  08:37 
Linux mcrowe-xps15-ubuntu 5.13.0-35-generic #40-Ubuntu SMP Mon Mar 7 08:03:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 ~  cat /etc/lsb-release                                                                                                                                                                           16  08:49 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
```

**Comment by Plasma** [comment]
Yes this a regression with the latest UI update, I had trouble setting up a build environment for it so haven’t had a chance to try and make a PR

**Comment by urz9999** [comment]
Have you tried version 0.12.0? Is this still an issue? We tried to reproduce this bug with the latest version to no avail.

**Comment by Plasma** [comment]
Just tried `0.12.0` and can reproduce:

1. Open Leapp UI
2. Sign on using AWS SSO
3. When you click "Allow" on the SSO prompt (after using credentials) you can't press CTRL+R anymore on eg, a Chrome browser
4. If I close Leapp UI it works again

**Comment by urz9999** [comment]
We have tried with electron-localshortcut in this commit: https://github.com/Noovolari/leapp/commit/c428547b0f865908b3d8d307a99273e87084dfae for branch:
**LEAP-570-verifica-leapp-blocks-ctrl-r-keybind-and-others-after-sso-window-closes-for-chrome-browser**

Can you try to build the solution and verify it on your side?

**Comment by fancywriter** [comment]
@urz9999 confirming that version from this branch works nice - Ctrl+R works again in other windows after minimizing the app.

**Comment by ericvilla** [comment]
Thank you @fancywriter for the feedback! I think we can close it as soon as a new release is available

**Comment by andreacavagna01** [comment]
Closing this issue since is fixed
