### ISSUE TITLE
v0.11.0 MFA push notification pops up every minute

### ISSUE THREAD

**Issue by jonasoneves** [Noovolari/leapp#248]
**Describe the bug**
After I installed the new version I've been receiving a pop window asking for MFA push every minute.
Even if I choose "do not challenge this device for the next 24 hours" I still see the window popping up
and disappearing very quickly every minute (with a blank page).

**Leapp Version**
v0.11.0

**To Reproduce**
1. Configure an AWS session with Okta IDP that requires MFA

**Expected behavior**
I'm not MFA challenged for the next 24 hours

**Screenshots**

<img width="575" alt="Screen Shot 2022-03-31 at 2 08 02 PM" src="https://user-images.githubusercontent.com/72263638/161122178-1c549b45-ba2b-4d87-a5ea-150507ce8c3b.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version 12.2.1
 - Leapp Version v0.11.0

**Comment by daveyu** [comment]
Noting that I experience the same thing with Onelogin. The pop up is disruptive because it steals focus.

**Comment by pethron** [comment]
Should be already fixed in master, you can try out from source to see if that solves the problem or wait for the next release.

**Comment by ericvilla** [comment]
Solved in [v0.11.1](https://www.leapp.cloud/releases) release. I'm going to close it

**Comment by jonasoneves** [comment]
This is still a problem, the difference is that it takes longer for the window to pop up (maybe like 1 hour?), even if I mark the option to not challenge me for the next 24 hours.
