### ISSUE TITLE
SSO login not compatible with Device Compliance in Azure AD

### ISSUE THREAD

**Issue by amartin-idea11** [Noovolari/leapp#326]
**Describe the bug**
When using SAML SSO from Azure AD, and a conditional access policy applies includes "Require device to be marked as compliant", the sign-in fails due to "The current browser is not supported, please use Microsoft Edge, Internet Explorer, Chrome or Firefox 91+ to access this application."

**Leapp Version**
0.14.2

**To Reproduce**
1. Use SAML SSO from Azure AD
2. End-user device managed by Intune
3. Conditional access policy requires the device be marked as compliant
4. Try to authenticate to an AWS IAM Role Federated session

**Expected behavior**
After authentication, I would expect the session to be activated

**Screenshots**
![image](https://user-images.githubusercontent.com/102931160/187800267-07976e72-bf25-4416-b961-36600fd11d1f.png)

![image](https://user-images.githubusercontent.com/102931160/187800338-c5262c22-21fa-4dea-be55-b8d1a2d060ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version 21H2
 - Leapp Version 0.14.2

**Additional context**
Because the app being authenticated against is "Microsoft App Access Panel", I can't set an exception to this app.

**Comment by c-sami** [comment]
Hi!
Did you try with In-browser auth. method?
It can be found when you edit AWS SSO integration:
![image](https://user-images.githubusercontent.com/92857136/187855461-c5faae41-86ed-4c2b-a1ac-c0d7943e1306.png)

**Comment by amartin-idea11** [comment]
Hi c-sami,
I am not using AWS Single Sign-on in this environment. I have no integrations configured, and the session is configured as IAM Role Federated from our Azure AD IDP as shown below. I had a poke around, but I couldn't find any similar setting for this kind of sign-in, but I could be missing it?

![image](https://user-images.githubusercontent.com/102931160/188021338-a702176c-9bb5-467b-8756-b7444bc738ad.png)

**Comment by andreacavagna01** [comment]
Hi, we just released v0.16.0. With that, an updated version of Chromium is online, and your problem should be solved. 

I'm going to close this issue. Feel free to reopen it if needed.

**Comment by amartin-idea11** [comment]
I've installed v0.16.1 and retried, but I am still getting the same behavior. The Azure log shows it as not receiving all the device info (e.g. no Device ID). 
![image](https://user-images.githubusercontent.com/102931160/201549184-505bebdc-226a-466a-b4c7-2e6c88eef5c9.png)


This is normally what you see when the application does not pass all the info along. In the case of Chrome, it requires the extension called "[Windows Accounts](https://chrome.google.com/webstore/detail/windows-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji)". 

My local Chrome install does have that add-in already, but if Leapp is using it's own packaged Chromium, possibly it will need this extension included before it'll work?

**Comment by ericvilla** [comment]
HI @amartin-idea11, have you managed to solve this issue on your own?

**Comment by amartin-idea11** [comment]
Hi @ericvilla no I haven't unfortunately. We ended up changing our policies so we're enforcing device compliance on specific apps instead of default w/ exceptions.
