### ISSUE TITLE
Import users fails

### ISSUE THREAD

**Issue by reidca** [Noovolari/leapp#509]
**Describe the bug**
When setting up team account, after the integration with AWS Identity Centre the wizard fails with unknown error when importing users and no users are imported

**Leapp Version**
0.23.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://app.leapp.cloud/integrations
2. Deploy agent by copying the template and launch the stack in the AWS management account where Identity Centre is configured
3. Test Connection - this works
4. Start to import users - this gets to a random percentage then fails with unknown error

**Expected behavior**
The users are shown

**Screenshots**
![image](https://github.com/Noovolari/leapp/assets/7325010/923e2bf9-b548-441d-80c8-0f0e06b52674)

**Additional context**
The cloudwatch log groups for the lambda function associated with the integration is getting a 500 error response back from the api:

      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://ual7x3rx1l.execute-api.eu-west-1.amazonaws.com/agent/update-status',

**Comment by ericvilla** [comment]
Hi @reidca! Thanks for reporting!
We are currently investigating this issue.

**Comment by andreacavagna01** [comment]
Hi @reidca I can confirm that the error is fixed now. 

There was a bug in the agent. Please delete the integration and the CloudFormation stack and start a new installation of a Leapp Integration. 

If you have any other problem, this will be our top 1 priority. 

Thanks for your patience

**Comment by reidca** [comment]
I have deleted and re-setup the integration and started scanning users again. Whilst this gets further it still fails unfortunately.

The error I see in the portal is: 
![image](https://github.com/Noovolari/leapp/assets/7325010/10b896e6-55ee-4cf1-abb6-48aed1f851c8)

**Comment by andreacavagna01** [comment]
Re-opening the issue. thanks for the feedback! I'm going to investigate it

**Comment by reidca** [comment]
any update on this?

**Comment by andreacavagna01** [comment]
The error is fixed now. 
You can delete the agent and the integration, and start installing it again. 

Let me if you have any problem

**Comment by reidca** [comment]
Deleted the integration, updated the cloudformation stackset with the new template. Recreated the integration and exactly the same error has occurred during the "Import Users" stage.

![image](https://github.com/Noovolari/leapp/assets/7325010/be3f51e1-b747-4832-99b7-d85db6621c4e)

**Comment by reidca** [comment]
@andreacavagna01 can you please re-open this issue as the problem is not resolved

**Comment by reidca** [comment]
any news on this? I am keen to try this but thus far it has been a very frustrating experience of constant bugs and little progress on resolving them. Or shall I just give up?

**Comment by ericvilla** [comment]
Hi @reidca, I'm sorry that the experience was frustrating. Reading all the comments, I've no evidence that you've deleted the CloudFormation stack and re-installed it again from scratch (you said you updated it), while creating the new integration

**Comment by reidca** [comment]
yes i updated it using the new template. 

An update with a new template is the same as recreating it unless there are parts of the stack that are not changed when the template has changed.

I will try again and see if this makes a difference.

**Comment by reidca** [comment]
I have tried this again, the 4th time now.

Deleted the Leapp integration
Deleted the CloudFormation template
Setup a new Leapp integration
Deployed the new cloudformation stack with the new template from the integration
Tested the connection
Starts importing users, gets to about 33% then fails with the same error again:

![image](https://github.com/Noovolari/leapp/assets/7325010/059fc3f9-86b2-4c86-b129-320c0a32788d)

**Comment by reidca** [comment]
@andreacavagna01 - any thoughts?
